### ISSUE TITLE
Decouple from imajus:common-helpers?

### ISSUE THREAD

**Issue by jankapunkt** [imajus/meteor-common-helpers#1]
I appreciate your work as the package works very well until the point of defining my own template helpers that have the same naming conventions like those of `imajus:common-helpers`.

Is it possible to decouple them from this package? We have built some global helpers with same naming but different functionality and I would like to use this package but not to refactor all my code for it.

Do you see any options here?

**Comment by jankapunkt** [comment]
another approach would be to allow users to define a prefix for the helpers to avoid conflicts.

**Comment by imajus** [comment]
Actually, the autoform-bootstrap4 is a bad place to use those helpers as it has to be as little dependent from other packages as possible. Moreover I've found only one template where "imajus:common-helpers" is used and I've found no place where "imajus:bootstrap-helpers" is used at all.
I've removed packages dependency, please update autoform-bootstrap4 to 0.0.3.
Let me know if you'll face any "missing helpers" issues. And please, create package related issues in https://github.com/imajus/autoform-bootstrap4

**Comment by jankapunkt** [comment]
Wow thank you for the fast response! I will give you an update in a minute.

**Comment by jankapunkt** [comment]
Works fine! I will close the issue. Thanks a lot!
